// Supabase persistence service for field scenarios
import { supabase } from '../lib/supabase';
import { FieldScenario } from '../Data/Models/fieldScenarios';

// Database table name
const TABLE_NAME = 'scenarios';

// Helper type for database row
interface ScenarioRow {
  id: string; // UUID primary key (auto-generated by DB)
  client_id: string; // App's scenario.id string (e.g., "scenario_...")
  user_id: string;
  name: string;
  description?: string;
  data: FieldScenario;
  created_at: string;
  updated_at: string;
}

// Result type for operations
export interface ScenarioResult<T> {
  data: T | null;
  error: Error | null;
}

/**
 * Get the current authenticated user ID
 * @throws Error if user is not authenticated
 */
async function getCurrentUserId(): Promise<string> {
  const { data: { session }, error } = await supabase.auth.getSession();
  
  if (error) {
    throw new Error(`Failed to get session: ${error.message}`);
  }
  
  if (!session?.user?.id) {
    throw new Error('User is not authenticated');
  }
  
  return session.user.id;
}

/**
 * Fetch all scenarios for the logged-in user, ordered by updated_at DESC
 * @returns Array of FieldScenario objects or error
 */
export async function listScenarios(): Promise<ScenarioResult<FieldScenario[]>> {
  try {
    const userId = await getCurrentUserId();
    
    const { data, error } = await supabase
      .from(TABLE_NAME)
      .select('data, client_id')
      .eq('user_id', userId)
      .order('updated_at', { ascending: false });
    
    if (error) {
      return {
        data: null,
        error: new Error(`Failed to list scenarios: ${error.message}`),
      };
    }
    
    // Extract FieldScenario objects from the data column
    // Ensure the client_id is preserved in the FieldScenario.id
    const scenarios: FieldScenario[] = (data || []).map((row: any) => {
      const scenario = row.data as FieldScenario;
      // Ensure id matches client_id (in case data.id is stale)
      return {
        ...scenario,
        id: row.client_id,
      };
    });
    
    return {
      data: scenarios,
      error: null,
    };
  } catch (error) {
    return {
      data: null,
      error: error instanceof Error ? error : new Error(String(error)),
    };
  }
}

/**
 * Fetch a single scenario by id (client_id)
 * @param id - Scenario client_id (app's scenario.id string)
 * @returns FieldScenario object or error
 */
export async function getScenario(id: string): Promise<ScenarioResult<FieldScenario>> {
  try {
    const userId = await getCurrentUserId();
    
    const { data, error } = await supabase
      .from(TABLE_NAME)
      .select('data, client_id')
      .eq('client_id', id)
      .eq('user_id', userId)
      .single();
    
    if (error) {
      return {
        data: null,
        error: new Error(`Failed to get scenario: ${error.message}`),
      };
    }
    
    if (!data) {
      return {
        data: null,
        error: new Error(`Scenario with id ${id} not found`),
      };
    }
    
    // Ensure id matches client_id
    const scenario = data.data as FieldScenario;
    return {
      data: {
        ...scenario,
        id: data.client_id,
      },
      error: null,
    };
  } catch (error) {
    return {
      data: null,
      error: error instanceof Error ? error : new Error(String(error)),
    };
  }
}

/**
 * Insert or update a scenario
 * On insert/update, always sets user_id = authenticated user id (required for RLS)
 * Uses client_id for conflict resolution (not UUID id)
 * @param fieldScenario - The FieldScenario object to save
 * @returns The saved FieldScenario or error
 */
export async function upsertScenario(
  fieldScenario: FieldScenario
): Promise<ScenarioResult<FieldScenario>> {
  try {
    const userId = await getCurrentUserId();
    
    // Ensure updated_at is set to current time
    const now = new Date().toISOString();
    const scenarioWithTimestamps: FieldScenario = {
      ...fieldScenario,
      updatedAt: now,
      createdAt: fieldScenario.createdAt || now,
    };
    
    // Build row with client_id (app's scenario.id) instead of UUID id
    const row: Omit<ScenarioRow, 'id' | 'created_at' | 'updated_at'> & {
      created_at?: string;
      updated_at?: string;
    } = {
      client_id: scenarioWithTimestamps.id, // Use app's scenario.id as client_id
      user_id: userId,
      name: scenarioWithTimestamps.name,
      description: scenarioWithTimestamps.description ?? null,
      data: scenarioWithTimestamps,
      created_at: scenarioWithTimestamps.createdAt,
      updated_at: scenarioWithTimestamps.updatedAt,
    };
    
    // Upsert by client_id (not by UUID id)
    const { data, error } = await supabase
      .from(TABLE_NAME)
      .upsert(row, {
        onConflict: 'client_id',
      })
      .select('data, client_id')
      .single();
    
    if (error) {
      return {
        data: null,
        error: new Error(`Failed to upsert scenario: ${error.message}`),
      };
    }
    
    // Ensure returned scenario has correct id (client_id)
    const scenario = data.data as FieldScenario;
    return {
      data: {
        ...scenario,
        id: data.client_id,
      },
      error: null,
    };
  } catch (error) {
    return {
      data: null,
      error: error instanceof Error ? error : new Error(String(error)),
    };
  }
}

/**
 * Delete a scenario by id (client_id)
 * @param id - Scenario client_id (app's scenario.id string) to delete
 * @returns Success status or error
 */
export async function deleteScenario(id: string): Promise<ScenarioResult<boolean>> {
  try {
    const userId = await getCurrentUserId();
    
    const { error } = await supabase
      .from(TABLE_NAME)
      .delete()
      .eq('client_id', id)
      .eq('user_id', userId);
    
    if (error) {
      return {
        data: null,
        error: new Error(`Failed to delete scenario: ${error.message}`),
      };
    }
    
    return {
      data: true,
      error: null,
    };
  } catch (error) {
    return {
      data: null,
      error: error instanceof Error ? error : new Error(String(error)),
    };
  }
}

/**
 * Generate a unique ID for new scenarios
 * Format: scenario_{timestamp}_{random}
 * This ID is used as client_id in the database
 */
export function generateScenarioId(): string {
  return `scenario_${Date.now()}_${Math.random().toString(36).substring(2, 11)}`;
}

